import = [
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"

[window.padding]
x = 10
y = 15

[font]
size = 14

[font.bold]
family = "MesloLGL Nerd Font"

[font.italic]
family = "MesloLGL Nerd Font"

[font.normal]
family = "MesloLGL Nerd Font"

[scrolling]
history = 1000
multiplier = 1

